# Write your code here :-)
print("========================")
print("      HELLO WORLD       ")
print("    by Logan Eerdmans   ")
print("========================")
print("")
print("Hello, World!")
name = input("What is your name?")
print(f"Thank you {name}, very cool!")